### PR TITLE
chore: add support to existing leaderboard APIs

### PR DESCRIPTION
**Pull request by gastongaiduk**
### Changes
- Adding support to these two endpoints
- - https://api-docs.retroachievements.org/v1/get-game-leaderboards.html
- - https://api-docs.retroachievements.org/v1/get-leaderboard-entries.html
- Fixing one table format
- Adding .idea folder to .gitignore

### CODE REVIEW

**Comment by gastongaiduk** [comment]
@official-wizard do you mind to review this one whenever you're available? I'd also like to know if we can make a release after this one is released.

**Comment by wescopeland** [comment]
Hey @gastongaiduk !

Unfortunately I don't know Kotlin so I'm not in a position I can review this PR. However, I do have a small request :-)
Would you be willing to also update api-docs to show these new Kotlin integrations, similar to what we have for other pages?

**Comment by official-wizard** [comment]
Merged & Deployed

**Comment by gastongaiduk** [comment]
> Hey @gastongaiduk !
> 
> 
> 
> Unfortunately I don't know Kotlin so I'm not in a position I can review this PR. However, I do have a small request :-)
> 
> Would you be willing to also update api-docs to show these new Kotlin integrations, similar to what we have for other pages?

Sure thing @wescopeland 👍

**Pull request merged**
